@startuml legend
skinparam dummy 0

!global $gitpath ?= "https://raw.githubusercontent.com/JohnLeyva/plantuml-assets/master"
!global $commonincludepath ?= $gitpath
!global $commonincludepath ?= "\code\puml\assets"
!global $this_legend_puml = $commonincludepath + '/legend.puml'
!global $this_style_puml = $commonincludepath + '/style.puml'

!include $this_style_puml

!unquoted procedure $legend_componentExample($type,$description='')
    rectangle $type <<$type>> [
        $description
    ]
!endprocedure

!procedure $legend_States_Content()
    $legend_componentExample(any)
    $legend_componentExample(review)
    $legend_componentExample(new)
    $legend_componentExample(alt)
    $legend_componentExample(wip)
    $legend_componentExample(done)
    $legend_componentExample(ready)
    $legend_componentExample(live)
    $legend_componentExample(notouch)
    $legend_componentExample(change)
    $legend_componentExample(temporary)
    $legend_componentExample(remove)
    '$legend_componentExample('out-of-scope')
        rectangle out_of_scope <<out-of-scope>> [
        ]

    any -> review <<review>>
    review -> new <<new>>
    new -> alt <<alt>>
    alt -> wip <<wip>>
    wip -> ready <<ready>>
    ready -> done <<done>>
    done -> live <<live>> 
    live -> notouch <<notouch>>
    notouch -> change <<change>>
    change -> temporary <<temporary>> 
    temporary -> remove <<remove>>
    remove -> out_of_scope <<out-of-scope>>
!endprocedure

!procedure $legend_Arrows_Content()
    rectangle A
    rectangle B
    rectangle C
    rectangle D
    rectangle E
    rectangle F
    rectangle G
    rectangle H
    rectangle I
    
    A -> B : Information Flow 
    B =\\ C : Push Message 
    C =r(0=> D : API POST
    D <=r(0= E : API GET
    E -> F <<eventually>> : Eventually
    F -|> G : Is A
    G *- H : Composed by
    H -0 I : Used In-process by
!endprocedure

!procedure $legend_Content()
    $legend_States_Content()
    $legend_Arrows_Content()
!endprocedure

!procedure $legend($open=0,$scale="0.5")
    !if ($open==0)
        legend
    !endif
{{
scale $scale
'title Conventions
!include $this_legend_puml
$legend_States_Content()
}}
{{
scale $scale
!include $this_legend_puml
$legend_Arrows_Content()
}}
More about [[$gitpath/style-simple.svg Conventions]]
<size:8> Plantuml %version() | %date("yyyy-MMM-dd") %filename()</size>
    !if ($open==0)
        end legend
    !endif
!endprocedure

'$legend_Content()
'$legend(0)

@enduml