@startuml option-notes
skinparam dummy 0

!function $option_label($text='',$desc='')
    !$linklabel = $GetName($text)
    !return '<color:purple><size:20><&tag>' + $linklabel + '</size></color>'
!endfunction

!function $option_pro()
    !return '<color:green><size:25><&thumb-up></size></color>'
!endfunction

!function $option_con()
    !return '<color:red><size:25><&thumb-down></size></color>'
!endfunction

!function $option_link($name)
    !if ($ishidden($name) == 1)
        !return '<<alt>> <<' + $name + '>> : . '
    !endif 
    !return '<<alt>> <<' + $name + '>> : ' + $option_label($name)
!endfunction

!procedure $note_start($name='', $target='')
    !if ($target=='')
        !global $global_last_note_target = $global_last_name
    !else
        !global $global_last_note_target = $target
    !endif

    !if ($name=='')
        !$name = $global_last_name + "_note"
    !endif
    !global $global_last_note_name = $name

    !if ($name == '')
    note on link
    !else
        !$handle = '$' + $name
        !$stereotype = '<<' + $name + '>>'
    note as $name $handle $stereotype
    !endif
!endprocedure

!procedure $note_end()
    end note
    !if ($global_last_note_target != '')
        !$handle = '$' + $global_last_note_name
        !$stereotype = '<<' + $global_last_note_name + '>>'
        !if (%not($ishidden($global_last_note_name)))
            !if (%not($ishidden($global_last_note_target)))
'                $global_last_note_name -- $global_last_note_target $stereotype
                $global_last_note_name -- $global_last_note_target $stereotype
            !endif
        !endif
    !endif
    !global $global_last_note_name = ''
    !global $global_last_note_target = ''
!endprocedure

!procedure note($text, $name='', $target='')
    $note_start($name, $target)
    $text
    $note_end()
!endprocedure

!procedure $note_test()
    component(note_test_component)
    note(abc)
!endprocedure
'$note_test()

!procedure $option_note_start($name='', $target='')
    $note_start($name, $target)
    !$str = $strReplace($name,$defaultWordSeparator,' ')
    $option_label($str)
!endprocedure

!procedure $option_note_end()
    $note_end()
!endprocedure

!procedure $option_test()
rectangle option_test $example {
    card option_test_card [
        $option_label("Opt ABC")
        $option_pro() : option_pro
        $option_con() : option_con
    ]

    component option_test_component

    option_test_card -- option_test_component $option_link(note_opt_test)
    $option_note_start(note_opt_test, option_test_card)
        description
        ---
        $option_pro() : option_pro
        $option_con() : option_con
    $option_note_end()
}
!endprocedure
'$option_test()

@enduml