@startuml style

!startsub BASIC

skinparam arrowcolor green
skinparam ArrowThickness 3
skinparam ArrowColor grey

!function $done($type = "any")
    !return "#lightblue|lightgreen"  
!endfunction

!function $notouch($type = "any")
    !return "#lightgreen|lightgray"  
!endfunction

!function $notouch_link($type = "any")
    !return "#gray"  
!endfunction

!function $exiting($type = "any")
    !return "#lightgreen"  
!endfunction

!function $existing($type = "any")
    !return "#lightgreen"  
!endfunction

!function $existing_link($type = "any")
    !return "#green"  
!endfunction

!function $new($type = "any")
    !return "#cyan"  
!endfunction

!function $new_link($type = "any")
    !return "#blue"  
!endfunction

!function $remove($type = "any")
    !return "#pink"  
!endfunction

!function $remove_link($type = "any")
    !return "#red"  
!endfunction

!function $temporary($type = "any")
    !return "#cyan|pink"  
!endfunction

!function $remove_future($type = "any")
    !return "#lightgreen|pink"  
!endfunction


!unquoted procedure $black_tag($text='',$desc='')
    note on link #black|lightgray
        <color:#white>$text</color><back:#white><color:#black>$desc</color></back>
    endnote
!endprocedure


legend
<back:#black><color:#white>Text Tag</color></back> | <color:#blue>=</color><back:$new()>New</back> |<back:$existing()>Existing</back> | <back:$remove()>Remove</back> | <back:$temporary()>Interim Component</back> | <back:$remove_future()>remove in another work stream</back> | <back:$notouch()>Existing no touch</back> | <back:$done()>Done</back>

<size:8> Plantuml %version() | %date("yyyy-MMM-dd") %filename()</size>
end legend

!endsub

!unquoted procedure $example_style($text='')
    component new $new() 
    component existing $existing() 
    component remove $remove()
    component temporary $temporary()
    component remove_future $remove_future() 
    component notouch $notouch() 
    component done $done() 
    new -[$new_link()]-> existing
        $black_tag(new_link)

    existing -[$remove_link()]-> remove
        $black_tag(remove_link)

    notouch --> existing
        $black_tag(default)

    existing -[$existing_link()]-> remove_future
        $black_tag(existing_link)
    
!endprocedure

'$example_style()

@enduml