@startuml style

!$diagram ?= 'none'
!if ($diagram != 'sequence')
left to right direction
!endif

!$commonincludepath ?= "https://raw.githubusercontent.com/JohnLeyva/plantuml-assets/master"
!include $commonincludepath/style-base.puml

'https://crashedmind.github.io/PlantUMLHitchhikersGuide/layout/layout.html
'allow_mixing
'skinparam monochrome true
'skinparam linetype polyline
'skinparam linetype ortho

'!include <azure/AzureCommon>
'!include <azure/Databases/AzureCosmosDb>
'!include <azure/Databases/AzureSqlDatabase>
'!include <cloudinsight/kafka>
'!include <cloudinsight/mongodb>
'!include <cloudinsight/java>
'!include <cloudinsight/java>




' C4

'!include <cloudinsight/mongodb>

!if ($C4_Include)
  !include <C4/C4_Deployment>
  !include <C4/C4_Container>
!endif

!procedure $C4_System($name,$description='')
    System($name, $GetName($name), $description)
!endprocedure

!procedure $C4_Person($name,$description='')
    Person($name, $GetName($name), $description)
!endprocedure


'!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
'!include osaPuml/Common.puml
'!include osaPuml/User/all.puml
'
'!include <office/Servers/database_server>
'!include <office/Servers/file_server>
'!include <office/Servers/application_server>
'!include <office/Concepts/service_application>
'!include <office/Concepts/firewall>

!$kafkaControlCenterUrl = 'https://kafka/{topic}'

!global $service_textSize = 50
!global $environment_textSize = 30
!global $external_textSize = 30

!global $defaultNoTitle = '_notitle'
!$defaultPartSeparator = '__'
!$defaultWordSeparator = '_'
!$scaleTextUp = 8
!$scaleTextDown = 4

!$scaleText = $scaleTextUp / $scaleTextDown

!procedure $rem($name)
    !$handle = '$' + $name
    !$stereotype = '<<' + $name + '>>'
    %set_variable_value($name + '_hidden', 1)
    remove $name
    remove $handle
    remove $stereotype
!endprocedure

!function $ishidden($name)
    !return %get_variable_value($name + '_hidden')
!endfunction

!procedure $hide($name)
    !$handle = '$' + $name
    !$stereotype = '<<' + $name + '>>'
    
    %set_variable_value($name + '_hidden', 1)

    hide $name
    hide $handle
    hide $stereotype
    skinparam ArrowThickness<<$name>> 0
    skinparam ArrowFontSize<<$name>> 0
!endprocedure

!procedure $show($name)
    !$handle = '$' + $name
    !$stereotype = '<<' + $name + '>>'
    show $name
    show $handle
    show $stereotype
!endprocedure

!unquoted function $link_type($name)
    !return '<<' + $name + '>> : ' + "<" + $name + '>' 
!endfunction

!function $strAppend($source,$append,$separator='')
    !if ( %strlen($source) > 0 && %strlen($append) > 0  )
        !return $source + $separator + $append
    !else
        !return $source + $append 
    !endif
!endfunction

!function $strPrepend($source,$prepend,$separator='')
    !if ( %strlen($source) > 0 && %strlen($prepend) > 0 )
        !return $prepend + $separator + $source
    !else
        !return $prepend + $source
    !endif
!endfunction

!function $strContains($text,$find) 
    !return %strpos($text,$find) >= 0
!endfunction

!function $strHasSuffix($text,$find) 
    !$len = %strlen($find)
    !if ($len == 0)
        !return %true()
    !endif
    !$pos = %strpos($text,$find)
    !if ($pos < 0) 
        !return %false()
    !endif
    !return ( %strlen($text) - $pos ) == $len
!endfunction

!procedure $strHasSuffix_test() {
card strHasSuffix_test [
    strHasSuffix_test
    IsSuffix    $strHasSuffix('aaabbb','bbb')
    Empty Suffix    $strHasSuffix('aaabbb','')
    Empty Suffix    $strHasSuffix('','')
    Empty Value    $strHasSuffix('','bbb')
    No Suffix    $strHasSuffix('aaa','cbb')
    No Suffix    $strHasSuffix('aaa','cccc')
]
!endprocedure
'$strHasSuffix_test()

!function $strReplace($str,$find,$replace)
    !$tail = $str
    !$len = %strlen($find)
    !$res = ""
    !$pos = 0
    !while $pos >= 0
        !$pos = %strpos($tail,$find)
        !if $pos >= 0
            !$head = %substr($tail, $0, $pos)
            !$tail = %substr($tail, $pos + $len)
            !$res = $res + $head + $replace
        !endif
    !endwhile
    !return $res + $tail
!endfunction
'node strReplace_Test as "$strReplace('<(a)>-<(b)>-<(c)>','<(','<')"

!function $strReverse($text,$map1='<{[(',$map2='>}])')
    !$pos = %strlen($text) -1
    !$result = ''
    !while $pos >= 0
        !$char = %substr($text, $pos, 1)
        !$mapPos = %strpos($map1,$char)
        !if $mapPos >= 0
            !$char = %substr($map2, $mapPos, 1)
        !else
            !$mapPos = %strpos($map2,$char)
            !if $mapPos >= 0
                !$char = %substr($map1, $mapPos, 1)
            !endif
        !endif
        !$result = $result + $char 
        !$pos = $pos - 1  
    !endwhile
    !return $result
!endfunction
'node strReverse_Test as "$strReverse('abc<123456789>def')"

!procedure $ShowJson($json,$text='=json')
    label l [
        $text
        $json
        {{json
        $json
        }}
    ]
!endprocedure

!function $strSegmentCount($str,$separator=$defaultPartSeparator)
    !if (%strlen($str) <= 0 )
        !return 0
    !endif
    !$res = $str
    !$pos = 1
    !$count = 1
    !while ($pos > 0)
        !$pos = %strpos($res,$separator)
        !if ($pos > 0)
            !$count = $count + 1
            !$res = %substr($res,$pos + %strlen($separator) )
        !endif
    !endwhile
    !return $count
!endfunction

!procedure $strSegmentCount_Test()
    !$count = $strSegmentCount(Part1__Part2__Part3,$defaultPartSeparator)
    !$count = $strSegmentCount('',$defaultPartSeparator)
    json strSegmentCount_json {
        "strSegmentCount" : "$count"
    }
!endprocedure
'$strSegmentCount_Test()

!function $strSegmentGet($str,$separator=$defaultPartSeparator,$count=(0-1))
    !$res = $str
    !$pos = 1
    !while ($pos >= 0)&&($count!=0)
        !$count = $count - 1
        !$pos = %strpos($res,$separator)
        !if ($pos >= 0)
            !$res = %substr($res,$pos + %strlen($separator) )
        !endif
    !endwhile
    !$pos = %strpos($res,$separator)
    !if ($pos >= 0)
        !$res = %substr($res,0,$pos)
    !endif
'    !$parts = %splitstr($str,$separator) ' Splits by char not by string so is not whats required
'    !foreach $item in $parts
'        !$res = $item
'    !endfor 
    !return $res
!endfunction
!procedure $strSegmentGet_Test() 
    node strSegmentGet_Test $example
    note right
        $strSegmentGet(Part1__Part2__Part3__Part4,'__',0)
        $strSegmentGet(Part1__Part2__Part3__Part4,'__')
        $strSegmentGet('Part1++Part2+Part3+Part4','+')
        $strSegmentGet('https://ukmail.atlassian.net/wiki/spaces/AR/pages/3691970663/Aure+Replacement+-+ConsignmentV1+-+Opsys+request+Batching','/')
    endnote
!endprocedure
'$strSegmentGet_Test()

!function $counter_get($name='counter') return %get_variable_value('autonumber_' + $name)

!function $counter_set($name='counter',$value)
    !return %set_variable_value('autonumber_' + $name, $value)
!end function

!function $counter($name='counter',$increment=1,$seed=1)
    !$current = $counter_get($name)
    !if (%not($current))
        !$result = $seed
    !else
        !$result = $current + $increment
    !endif
    !$nop = $counter_set($name, $result)
    !return $result
!end function

!function $counter_print($name='counter',$increment=1,$seed=1)
    !return '<back:black><color:white>[' + $counter($name, $increment, $seed) + ']</color></back>' 
!end function

!function $link_id($name) 
    !return '<<thick>>' + '<<' + $name + '>>' + ' :' + $counter_print() + $GetName($name)
!end function

!function $link_entity($name) 
    %set_variable_value('entity_last', $name)
    !return %chr(34) + $name + %chr(34)
!end function

!global $highlight_start = '<('
!global $highlight_end = ')>'

!function $highlight($str,$start=$highlight_start,$end=$highlight_end,$color='red')
    !$res = $strReplace($str,$start,"<color:" + $color + ">")
    !$res = $strReplace($res,$end,"</color>")
    !return $res
!endfunction
'node highlight_test as "$highlight('<(a)>-<(b)>-<(c)>')"

!unquoted function $stereotype($str)
    !if ($str=='')
        return $str
    !endif

    !$result = ''
    !$parts = %splitstr($str,";") 
    !foreach $item in $parts
        !if (%substr($item,0,1) != "#" )
            !$result = $result + '<<' + $item + '>>'
        !endif
    !endfor 
    !return $result
!endfunction
'[ <<aa>> $stereotype(one;two) <<cc>>]

!function $link($text, $url)
    !if (%substr($text,0,1) == '/')
        !$text = $strSegmentGet($url,$text)
    !endif
    !$text = $strReplace($text,'+',' ')
    !return "[[" + $url + " " + $text + "]]"
!endfunction
!procedure $link_Test()
    card link_Test [
        $link(aa+-+bb,http://google.com)
        $link('/Aure+Replacement+',https://ukmail.atlassian.net/wiki/spaces/AR/pages/3691970663/Aure+Replacement+-+ConsignmentV1+-+Opsys+request+Batching)
    ]
!endprocedure
'$link_Test()

!function $linkRes($str)
    !$separator="|"
    !$count = $strSegmentCount($str,$separator) -  1
    !$res = ''
    !while ($count >= 0)
        !$part = $strSegmentGet($str,$separator,$count)
        !$key = $strSegmentGet($part,'!',0)
        !$url = $strSegmentGet($part,'!',1)
        !$keytag = "<" + $key + ">"
        !$res = $link($keytag, $url) + " " + $res
        !$count = $count - 1
    !endwhile 
    !return $res 
!endprocedure
!procedure $linkRes_Test()
    label linkRes [
        $linkRes('A!http://aaa.com|B!http://bbb.com|C!http://ccc.com')
    ]
!endprocedure
'$linkRes_Test()

!function $linkObj($json_object)
    !$res = ''
    !if (%get_json_type($json_object) == "object")
        !foreach $key in %get_json_keys($json_object)
            !$keytag = "<" + $key + ">"
            !$res = $res + " " + $link($keytag,$json_object[$key])
        !endfor
    !endif
    !return $res 
!endprocedure
!procedure $linkObj_Test()
    !$url_data = { 
        "A" : "http://aaa.com",
        "B" : "http://bbb.com",
        "C" : "http://ccc.com"
      }
    label linkObj [
        $linkObj($url_data)
    ]
!endprocedure
'$linkObj_Test()

!function $GetName($str)
    !$name = $strSegmentGet($str)
    !$name = $strReplace($name,$defaultWordSeparator,' ')
    !return $name
!endfunction

!function $strContainsSegment($list,$find,$separator)
    !if ( $list == $find )
        !return %true()
    !endif
    !if ( $strContains($list,$separator + $find + $separator) )
        !return %true()
    !endif
    !if ( %strpos($text,$find + $separator) == 0 )
        !return %true()
    !endif
    !if ( %strpos($text,$separator + $find) == %strlen($list) - %strlen($find) )
        !return %true()
    !endif
    !return %false()
!endfunction

!global $label_Inventory_store = ''
!procedure $label_Inventory_add($value)
    !if (%strlen($value)>0)
        !global $label_Inventory_separator = '|'
        !global $label_Inventory_store = $strAppend($label_Inventory_store,$value,$label_Inventory_separator)
    !endif
!endprocedure
!procedure $label_Inventory_add_test()
    $label_Inventory_add(BBBb)
    $label_Inventory_add(AAAAA)
    card label_Inventory_add_test [
        $label_Inventory_store
    ]
!endprocedure
'$label_Inventory_add_test()


!global $label_NoTitle_counter = 0
!function $label($str='',$data=0,$sizeArg=0)
    $label_Inventory_add($str)

    !if $str == ''
        !$label_NoTitle_counter = $label_NoTitle_counter + 1
        !$str = $global_last_name + "_" + $defaultNoTitle + "_" + $label_NoTitle_counter
    !endif

    !$dataname = "$" + $str + "_data"
    !$links = ''
    !if (%get_json_type($data) != "object")
        !if (%variable_exists($dataname))
            !$data = %get_variable_value($dataname)
        !endif
    !endif

    !if (%get_json_type($data) == "object")
        !$links = $linkObj($data.url)
        !if ($data.text_size > 0)
            !$sizeArg = $data.text_size
        !endif
    !endif

    !if (%get_json_type($data) == "string")
        !if (%strpos($data,"://") > 0)
            !$links = $linkRes($data.url)
            !if ($data.text_size > 0)
                !$sizeArg = $data.text_size
            !endif
        !endif
    !endif

    !$sizeArg = %intval($sizeArg)
    !$size = ( $sizeArg * $scaleTextUp / $scaleTextDown )

    !$parts = %splitstr($str,";")
    !$res = $str

    !if ($size > 0)
        !$sizeStart = '<size:' + $size + '>'
        !$sizeEnd = '</size>'
    !else
        !$sizeStart = ''
        !$sizeEnd = ''
    !endif

    !$name = $GetName($str)
    !$entityLevel = $strSegmentCount($str)

    !global $global_last_name = $str
    !global $global_last_entityLevel = $entityLevel

    !if ($strContains($str,$defaultNoTitle))
        !$res = $res + ' as " "'
    !else
        !$labelAs = $sizeStart + $name + $sizeEnd + $links
        !if (%strlen($labelAs) > 0 )
            !$res = $res + ' as "' + $labelAs + '" '
        !endif
    !endif

    !return $res
!endfunction

!procedure $label_Test() 
    !global $Any_Service_3_data1 = { "url" : { 
        "A" : "http://aaa.com",
        "B" : "http://bbb.com",
        "C" : "http://ccc.com"
      },
      "text_size" : 40 }

    rectangle label_Test [
        == label_Test
        ---
            No Size
            $label(Any_Service_1)
        ---
            Size = 30
            $label(Any_Service_2,0,20)
        ---
            $label(Any_Service_3_notitle,$Any_Service_3_data1,15)
        ---
            $label(Any_Service_4,'F!http://aaa.com|G!http://bbb.com|H!http://ccc.com',15)
    ]
!endprocedure
'$label_Test()


!unquoted procedure $scale($type, $name, $action = '', $factor = 4)
    !$scale2 = $factor * $scaleText
    label $name [
    {{
        scale $scale2
        $type $label($name,$action,10)
    }}
    ]
!endprocedure
!procedure $scale_Test() 
    $scale(actor/,ACTOR_T,'')
!endprocedure
' $scale_Test()

!procedure title($text)
    !$message = $GetName($text)
    title <size:30>$message / %date("yyyy-MM-dd")
!endprocedure 

!function $service($name = '', $action = '')
    !return "frame " + $label($name,$action,$service_textSize) + " <<service>> " 
!endfunction

!function $environment($name = '', $action = '')
    !return "rectangle " + $label($name, $action,$environment_textSize) + " <<environment>> "
!endfunction

!function $external($name = '', $action = '')
    !return "cloud " + $label($name,$action,$external_textSize) + " <<environment>> "
!endfunction

!function $transaction($name = '', $action = '') {
    !return "hexagon " + $label($name,$action) + " <<transaction>> "
!endfunction

'entity icons

!procedure $entity($name,$type,$size=0,$color=0)
    !$name_inner=$name + "_inner"
    rectangle $label($name) {
        label $name_inner [
            $icon($type,$size,$color)
        ]
    }
!end procedure

!procedure email($name, $size=0,$color=0)
    $entity($name, 'email', $size, $color)
!end procedure

!procedure timer($name,$size=0,$color=0)
    $entity($name, 'timer', $size, $color)
!end procedure

!procedure parcel($name,$size=100,$color="RosyBrown")
    $entity($name,parcel,$size,$color)
!end procedure

!procedure computer($name,$size=100,$color="RosyBrown")
    $entity($name,monitor,$size,$color)
!end procedure

' entities end

!function SetEntityType($type='')
    $global $EntityType = $type
    !return $type
!endfunction 

!function actor          ($name='',$data='') !return SetEntityType('actor'         ) + ' ' + $label($name,$data)
!function actor2         ($name='',$data='') !return SetEntityType('actor/'        ) + ' ' + $label($name,$data)
!function agent          ($name='',$data='') !return SetEntityType('agent'         ) + ' ' + $label($name,$data)
!function artifact       ($name='',$data='') !return SetEntityType('artifact'      ) + ' ' + $label($name,$data)
!function boundary       ($name='',$data='') !return SetEntityType('boundary'      ) + ' ' + $label($name,$data)
!function card           ($name='',$data='') !return SetEntityType('card           ) + ' ' + $label($name,$data)
!function circle         ($name='',$data='') !return SetEntityType('circle'        ) + ' ' + $label($name,$data)
!function cloud          ($name='',$data='') !return SetEntityType('cloud'         ) + ' ' + $label($name,$data)
!function collections    ($name='',$data='') !return SetEntityType('collections'   ) + ' ' + $label($name,$data)
!function component      ($name='',$data='') !return SetEntityType('component'     ) + ' ' + $label($name,$data)
!function control        ($name='',$data='') !return SetEntityType('control'       ) + ' ' + $label($name,$data)
!function database       ($name='',$data='') !return SetEntityType('database'      ) + ' ' + $label($name,$data)
!function entity         ($name='',$data='') !return SetEntityType('entity'        ) + ' ' + $label($name,$data)
!function file           ($name='',$data='') !return SetEntityType('file'          ) + ' ' + $label($name,$data)
!function folder         ($name='',$data='') !return SetEntityType('folder'        ) + ' ' + $label($name,$data)
!function frame          ($name='',$data='') !return SetEntityType('frame'         ) + ' ' + $label($name,$data)
!function hexagon        ($name='',$data='') !return SetEntityType('hexagon'       ) + ' ' + $label($name,$data)
!function interface      ($name='',$data='') !return SetEntityType('interface'     ) + ' ' + $label($name,$data)
!function label          ($name='',$data='') !return SetEntityType('label'         ) + ' ' + $label($name,$data)
!function node           ($name='',$data='') !return SetEntityType('node'          ) + ' ' + $label($name,$data)
!function package        ($name='',$data='') !return SetEntityType('package'       ) + ' ' + $label($name,$data)
!function person         ($name='',$data='') !return SetEntityType('person'        ) + ' ' + $label($name,$data)
!function queue          ($name='',$data='') !return SetEntityType('queue'         ) + ' ' + $label($name,$data)
!function rectangle      ($name='',$data='') !return SetEntityType('rectangle'     ) + ' ' + $label($name,$data)
!function stack          ($name='',$data='') !return SetEntityType('stack'         ) + ' ' + $label($name,$data)
!function storage        ($name='',$data='') !return SetEntityType('storage'       ) + ' ' + $label($name,$data)
!function usecase        ($name='',$data='') !return SetEntityType('usecase'       ) + ' ' + $label($name,$data)
!function usecase2       ($name='',$data='') !return SetEntityType('usecase/'      ) + ' ' + $label($name,$data)

'file(abc)

!function abstract_class ($name='',$data='') !return SetEntityType('abstract class') + ' ' + $label($name,$data)
!function class          ($name='',$data='') !return SetEntityType('class'         ) + ' ' + $label($name,$data)
!function enum           ($name='',$data='') !return SetEntityType('enum'          ) + ' ' + $label($name,$data)
!function abstract       ($name='',$data='') !return SetEntityType('abstract'      ) + ' ' + $label($name,$data)
!function annotation     ($name='',$data='') !return SetEntityType('annotation'    ) + ' ' + $label($name,$data)
!function circle         ($name='',$data='') !return SetEntityType('circle'        ) + ' ' + $label($name,$data)
!function diamond        ($name='',$data='') !return SetEntityType('diamond'       ) + ' ' + $label($name,$data)
!function entity         ($name='',$data='') !return SetEntityType('entity'        ) + ' ' + $label($name,$data)
!function exception      ($name='',$data='') !return SetEntityType('exception'     ) + ' ' + $label($name,$data)
!function metaclass      ($name='',$data='') !return SetEntityType('metaclass'     ) + ' ' + $label($name,$data)
!function protocol       ($name='',$data='') !return SetEntityType('protocol'      ) + ' ' + $label($name,$data)
!function stereotype     ($name='',$data='') !return SetEntityType('stereotype'    ) + ' ' + $label($name,$data)
!function struct         ($name='',$data='') !return SetEntityType('struct'        ) + ' ' + $label($name,$data)
!function port           ($name='',$data='') !return SetEntityType('port'          ) + ' ' + $label($name,$data)
!function portIn         ($name='',$data='') !return SetEntityType('portIn'        ) + ' ' + $label($name,$data)
!function portOut        ($name='',$data='') !return SetEntityType('portOut'       ) + ' ' + $label($name,$data)

'Sequence Diagram
!function box          ($name='',$data='') !return 'box '         + $label($name,$data)
!function participant  ($name='',$data='') !return 'box '         + $label($name,$data)


!function $push() return "-->"

!function $transactionLink()
    !return ' *--> "<<transaction>>"'
!endfunction

!procedure $topic($name,$format='',$icon='')
    !$topicName = $strReplace($name,'_queue','')
    !$topicName = $strReplace($name,'_topic','')
    !$topicName = $strReplace($name,'_','-')
    !$topicName = $strReplace($name,'--','_')
    !$topicUrl = $strReplace($kafkaControlCenterUrl,'{topic}',$topicName)
    !$topicLink = $link($topicName,$topicUrl)
    !$alias = $topicLink
    !$alias = $strPrepend($alias,$icon,' ')
    !$alias = $strAppend($alias,$highlight($format),'\n')
    queue $name as "$alias"
    $label_Inventory_add($name)
!endprocedure

!procedure $kafka($name,$format='')
    $topic($name,$format,"<$kafka*0.5>")
!endprocedure

!procedure $topic_message($topicname,$messageType) 
    !$notename = $topicname + "_" + $messageType
    note as $notename
        %invoke_procedure($messageType)
    end note
    $topicname -- $notename
!endprocedure

!unquoted procedure $tag($text='',$desc='', $tagcolor='#black')
    note on link $tagcolor|lightgray
        <&cog><color:#black>$text</color><back:#white><color:#black>$desc</color></back>
    endnote
!endprocedure

!unquoted procedure $black_tag($text='',$desc='')
    note on link #black|lightgray
        <&cog><color:#black>$text</color><back:#white><color:#black>$desc</color></back>
    endnote
!endprocedure

' Options

!unquoted procedure PK($field)
    <u>$field</u>
!endprocedure

!unquoted procedure NotUsed($field)
    <s:red>$field</s>
!endprocedure

!function $option_label($text='',$desc='')
    !$linklabel = $GetName($text)
    !return '<color:purple><size:20><&tag>' + $linklabel + '</size></color>'
!endfunction

!function $option_pro()
    !return '<color:green><size:25><&thumb-up></size></color>'
!endfunction

!function $option_con()
    !return '<color:red><size:25><&thumb-down></size></color>'
!endfunction

!function $option_link($name)
    !if ($ishidden($name) == 1)
        !return '<<alt>> <<' + $name + '>> : . '
    !endif 
    !return '<<alt>> <<' + $name + '>> : ' + $option_label($name)
!endfunction

!procedure $note_start($name='', $target='')
    !if ($target=='')
        !global $global_last_note_target = $global_last_name
    !else
        !global $global_last_note_target = $target
    !endif

    !if ($name=='')
        !$name = $global_last_name + "_note"
    !endif
    !global $global_last_note_name = $name

    !if ($name == '')
    note on link
    !else
        !$handle = '$' + $name
        !$stereotype = '<<' + $name + '>>'
    note as $name $handle $stereotype
    !endif
!endprocedure

!procedure $note_end()
    end note
    !if ($global_last_note_target != '')
        !$handle = '$' + $global_last_note_name
        !$stereotype = '<<' + $global_last_note_name + '>>'
        !if (%not($ishidden($global_last_note_name)))
            !if (%not($ishidden($global_last_note_target)))
                $global_last_note_name -- $global_last_note_target $stereotype
            !endif
        !endif
    !endif
    !global $global_last_note_name = ''
    !global $global_last_note_target = ''
!endprocedure

!procedure note($text, $name='', $target='')
    $note_start($name, $target)
    $text
    $note_end()
!endprocedure

!procedure $note_test()
    component(note_test_component)
    note(abc)
!endprocedure
'$note_test()

!procedure $option_note_start($name='', $target='')
    $note_start($name, $target)
    !$str = $strReplace($name,$defaultWordSeparator,' ')
    $option_label($str)
!endprocedure

!procedure $option_note_end()
    $note_end()
!endprocedure

!procedure $option_test()
rectangle option_test $example {
    card option_test_card [
        $option_label("Opt ABC")
        $option_pro() : option_pro
        $option_con() : option_con
    ]

    component option_test_component

    option_test_card -- option_test_component $option_link(note_opt_test)
    $option_note_start(note_opt_test, option_test_card)
        description
        ---
        $option_pro() : option_pro
        $option_con() : option_con
    $option_note_end()
}
!endprocedure
'$option_test()

' Examples

!procedure messageTypeExample ()
    {{
        json jsonschema {
            "Key" : "Header.CorrelationID",
            "Value" : {
                "EntityId" : "string",
                "status" : ["Success", "Warning", "Failed"],
                "Errors[]" : "record"
            }
        }
    }}
!end procedure


'big example

!unquoted procedure $componentExample($type,$description='')
        rectangle $type <<$type>> [
            $description
            ]   
!endprocedure

!procedure $example_style()
    rectangle example_style $example {
        together {
            component anyComponent
            $componentExample(new)
            $componentExample(existing)
            $componentExample(remove)
            component temporary <<new>> <<temporary>>
            $componentExample(notouch)
            $componentExample(done)
            $componentExample(ready)
            $componentExample(wip)
            $componentExample(change)
            component alternative <<alt>>

            new ..|> anyComponent : Realization 
            usecase anyUseCase as "use case"
            actor anyActor as "user/system" 
            actor stakeholder  
            stakeholder --|> anyActor : is as
            stakeholder -- anyUseCase

            existing --> remove $link_type(remove)
            existing --> notouch $link_type(notouch)
            existing --> change $link_type(change) 
            change --> done $link_type(change)
            new --> done $link_type(new)
                $black_tag(new_link)
            wip --> done
            ready --> done
            done --> existing $link_type(existing)

            new --|> anyUseCase : Implements

            rectangle "No in the project scope" <<out-of-scope>> {
                component remove_future <<remove>>
            }
            
            rectangle "In the scope of another workstream" <<next-phase>> {
                component change_future <<change>>

                existing --> remove_future <<existing>>
                    $black_tag(existing_link)
                
                existing --> change_future $link_type(eventually)

                new --> temporary $link_type(temporary)
                temporary --> remove_future $link_type(out-of-scope)
                new --> alternative $link_type(alt)
                    $tag(alt_link)
            }
        }
  
    $service(Any_Service_Group) <<existing>> {
        $service(Any_Service_Group__Any_Service) <<new>> {
            rectangle() {
            $environment(Any_Service_Group__Any_Service__AAA__Any_Environment) <<new>> {

                database anyDatabase as "Queryable\nstorage"
                file anyFile as "File\nstorage"
                node process {
                    entity anyEntity as "Aggregate / Entity"
                    control anyControl as "Control / Controller"
                    boundary anyBoundary as "Boundary"
                    anyControl -l-> anyEntity
                    anyBoundary -l-> anyControl
                    anyActor --> anyBoundary
                }

                anyControl --> anyDatabase : POST/PUT/PATCH
                anyDatabase --> anyControl : GET
                anyControl --> anyFile : Save
                anyFile --> anyControl : Retrieve

                $kafka(Topic_outbound,'<(MessageType)>-from_<(source)>-processed') <<outbound>>
                $topic(Topic_inbound,'<(MessageType)>-from_<(source)>-accepted') <<inbound>>
                $topic_message(Topic_outbound,messageTypeExample)

                anyControl --\\ Topic_outbound : PUSH
                Topic_inbound --\\ anyControl : PULL

                interface ApiGateway as "ApiGateway Proxy"
                ApiGateway -d- anyBoundary
            }
            }
        }
    } 
}
!endprocedure

!procedure $Transaction_example()
frame Transaction_Diagram_convention $example {

    database Transaction_resource_A 

    $transaction(Any_TransactionScope) {
        control $label(Control_With_TransactionScope)
    }

    database Transaction_resource_B
    File No_Transaction_resource_C

    Transaction_resource_A *--> Control_With_TransactionScope <<transaction>> : read
        note on link
            **In transaction** 
            Use Composition Arrow 
            <color:red>*--></color>
        endnote
    Control_With_TransactionScope *--> Transaction_resource_B <<transaction>> : write
        note on link
            In transaction 
        endnote
    Control_With_TransactionScope --> No_Transaction_resource_C : write
        note on link
            **NOT in transaction** 
        endnote
}
!endprocedure

!procedure $model_notation_example()
frame(model_notation) $example {
     label model_notation_label [
         {{
             'left to right direction
             'skinparam Nodesep 100
             skinparam Ranksep 35

             Entity "Car" as Car {}
             Class "Vehicle" as Vehicle {
                 PK(Primary Key)
                 Normal Property
             }
             enum SetOfValues {
                 PK(default)
                 Active
                 NotUsed(Not Used)
             }

             Car -|> Vehicle : Is a
             Vehicle "Composed by" *---{ "many" Part  
             Part - SetOfValues
         }} 
     ]
}
!endprocedure

!procedure $flow_vs_dependency()
frame(flow_vs_dependency) $example {
    
    rectangle flow_vs_dependency_A as " " {
        control publisher_topic
        queue topic
        control consumer_topic
        publisher_topic -r-\\ topic : Publish
        topic -r-\\ consumer_topic : Consume
    }

    rectangle flow_vs_dependency_B as " " {
        control persister_storage
        database storage
        control querier_storage

        persister_storage -r-> storage : Store
        storage -r-> querier_storage : Query
    }

    rectangle flow_vs_dependency_C as " " {
        control API_client_POST
        interface API_Gateway_POST
        boundary API_Backend_POST

        API_client_POST -r(0-> API_Gateway_POST : POST
        API_Gateway_POST -r(0-> API_Backend_POST : POST
    }

    rectangle flow_vs_dependency_D as " " {
        control API_client_GET
        interface API_Gateway_GET
        boundary API_Backend_GET

        API_client_GET <-r(0- API_Gateway_GET : GET
        API_Gateway_GET <-r(0- API_Backend_GET : GET
    }

    flow_vs_dependency_A -- flow_vs_dependency_B <<hide>>
    flow_vs_dependency_B -- flow_vs_dependency_C <<hide>>
    flow_vs_dependency_C -- flow_vs_dependency_D <<hide>>
}
!endprocedure

!procedure $style_test_all()
    rectangle {
    $example_style()
    $option_test()
    $Transaction_example()
    $flow_vs_dependency()
    $model_notation_example()
    $legend()
    }
!endprocedure

!function $label_filter($suffix,$template)
    !$count = $strSegmentCount($label_Inventory_store,$label_Inventory_separator)
    !$result = ""
    !while ($count > 0)
        !$count = $count - 1
        !$labelValue = $strSegmentGet($label_Inventory_store,$label_Inventory_separator,$count)
        !if ($strHasSuffix($labelValue,$suffix))
            !$countLabelSegmentCount = $strSegmentCount($labelValue)
            !$resultItem = ""
            !$countLabelSegmentPos = 0
            !while ($countLabelSegmentPos < $countLabelSegmentCount)
                !$labelValueSegment = $strSegmentGet($labelValue, $defaultPartSeparator, $countLabelSegmentPos)
                !$resultItem = $strAppend($resultItem, $labelValueSegment, $defaultPartSeparator)
'                !if ( %not($strContainsSegment($result, $resultItem, $label_Inventory_separator))&& $strContainsSegment($label_Inventory_store, $resultItem, $label_Inventory_separator) )
                !if ( %not($strContainsSegment($result, $resultItem, $label_Inventory_separator)))
                    !$result = $result + $strReplace($template,"%",$resultItem)
                !endif
                !$countLabelSegmentPos = $countLabelSegmentPos + 1
            !endwhile
            '!$result = $result + $strReplace($template,"%",$resultItem)
        !endif
    !endwhile
    !return $result
!endfunction

!procedure $label_filter_test()
    !$value = $label_filter('Environment',"%" + %newline())
    card label_filter_test_jsonc [
        $value
    ]
!endprocedure

'$style_test_all()
'$label_filter_test()

!procedure $label_hide($suffix)
    $label_filter($suffix,"hide %" + %newline())
!endprocedure

!procedure $label_show($suffix)
    $label_filter($suffix,"show %" + %newline())
!endprocedure

!procedure $label_remove($suffix)
    $label_filter($suffix,"remove %" + %newline())
!endprocedure

!unquoted function $rel_inv($relation)
    !$left = $GetPart($relation,' ',0)
    !$rel = $GetPart($relation,' ',1)
    !$right = $GetPart($relation,' ',2)
    !$rel = $strReverse($rel)
    !return $right + ' ' + $rel + ' ' + $left
!endfunction

@enduml