@startuml style-base

' !$commonincludepath ?= "\code\puml\assets"
!global $icon_Size ?= 50

!$defaultColor = '#white'
!$defaultPartSeparator = '__'
!$defaultWordSeparator = '_'

!procedure test_sequence()
    !global $diagram = 'sequence'
    box
    participant aa
    end box 
    aa --> aa
!endprocedure
'test_sequence()

!function $strReplace($str='',$find='',$replace='')
    !$tail = $str
    !$len = %strlen($find)
    !if ($len == 0)
        !return $str
    !endif
    !$res = ""
    !$pos = 0
    !while $pos >= 0
        !$pos = %strpos($tail,$find)
        !if $pos >= 0
            !$head = %substr($tail, $0, $pos)
            !$tail = %substr($tail, $pos + $len)
            !$res = $res + $head + $replace
        !endif
    !endwhile
    !return $res + $tail
!endfunction

!function $text_literal($text)
    !$special = %splitstr("~ " + %chr(34) + " < _ / *"," ")
    !foreach $item in $special
        !$text = $strReplace($text, $item ,'~' + $item)
    !endfor
    !return $text
!endfunction

!procedure $assert($expected='',$actual='',$description='')
    !global $assert_count ?= 0
    !$assert_count = $assert_count + 1
    !$assert_name = 'assert_' + $assert_count
    !if ($expected != $actual)
        !if ($diagram != 'sequence')
        rectangle #red {
            !$actual_literal = $text_literal($actual)
            !$expected_literal = $text_literal($expected)
            !if ($actual_literal == $actual)
                !$actual_literal = ''
            !endif
            !if ($expected_literal == $expected)
                !$expected_literal = ''
            !endif

            card $assert_name##_card [
                = ASSERT FAILED <:fire:> 
                $description

                |=  |= value |= len | literal |
                | actual | $actual | %strlen($actual) | $actual_literal |
                | expected | $expected | %strlen($expected) | $expected_literal |
            ]

        }
        !else if ($diagram == 'sequence')
            assert --> assert  
            note over assert #red : ASSERT FAILED \n $expected != $actual \n $description
        !endif 
    !endif
!endprocedure
$assert('aaa','aaa','description')
'$assert('aaa',%chr(34) + 'aaa' + %chr(34) ,'description')
'$assert('<color:blue>aaa bbb','<color:red>aaa __bbb__' ,'description')

!procedure $set_direction()
    !$diagram ?= 'none'
    !if ($diagram != 'sequence')
        left to right direction
    !endif
!endprocedure

' Review https://github.com/tupadr3/plantuml-icon-font-sprites

!function $remark($text,$color=red) return "<color:" + $color+ ">" + $text + "</color>"  

!function $notouch      ($type = "any") return "#lightgray"
!function $notouch_link ($type = "any") return "#gray"
!function $exiting      ($type = "any") return $existing($type)
!function $existing     ($type = "any") return "#lightgreen"
!function $existing_link($type = "any") return "#green"
!function $new          ($type = "any") return "#powderBlue"
!function $new_link     ($type = "any") return "#blue"
!function $change       ($type = "any") return %lighten(Yellow,70)  

!function $change_link  ($type = "any") return "#burlywood"  
!function $remove       ($type = "any") return "#pink"
!function $remove_link  ($type = "any") return "#red"
!function $alt          ($type = "any") return "#plum"
!function $alt_link     ($type = "any") return "#purple"
!function $ready        ($type = "any") return "#green"
!function $done         ($type = "any") return "#green"
!function $temporary    ($type = "any") return "#powderBlue|pink"
!function $remove_future($type = "any") return "#lightgreen|pink"
!function $change_future($type = "any") return "#lightgreen|yellow"

skinparam defaultTextAlignment left
skinparam fileBackgroundColor #white
skinparam LineThickness 3
skinparam ArrowLollipopColor #blue
skinparam NoteBorderThickness 1.5
'skinparam WrapWidth 200
skinparam Nodesep 40
skinparam Ranksep 50

!global $style__out_of_scope__LineThickness = 5
!global $style__out_of_scope__LineStyle = 50
!global $style__out_of_scope__DiagonalCorner = 20


'C4
'!include <C4/C4_Deployment>
'!include <C4/C4_Container>
'!include <C4/C4_Container>

' SET STYLE START {
    !global $current_artifact_state = ''

    !procedure style_set($back='transparent',$line='black', $LineThickness = 1, $LineStyle = 0, $FontSize = 11)
    <style>
    group {
    !if ($back!='')
        Backgroundcolor $back
    !endif
    !if ($line!='')
        LineColor $line
    !endif
    !if ($LineThickness != '')
        LineThickness $LineThickness
    !endif
    !if ($LineStyle != '')
        LineStyle $LineStyle
    !endif
    !if ($FontSize != -100)
        FontSize $FontSize
    !endif
        ' FontStyle plain
    }
    </style>
    !endprocedure

    !procedure style_reset()
        !$current_artifact_state = ''
        style_set()
    !endprocedure

    !procedure style_set_new()
        !$current_artifact_state = 'new'
        style_set($new())
    !endprocedure

    !procedure style_set_notouch()
        !$current_artifact_state = 'notouch'
        style_set($notouch())
    !endprocedure

    !procedure style_set_change()
        !$current_artifact_state = 'change'
        style_set($change())
    !endprocedure

    !procedure style_set_existing()
        !$current_artifact_state = 'existing'
        style_set($existing())
    !endprocedure

    !procedure style_set_ready()
        !$current_artifact_state = 'ready'
        style_set('transparent',$ready(),4,10)
    !endprocedure

    !procedure style_set_done()
        !$current_artifact_state = 'done'
        style_set('transparent',$done(),4,10)
    !endprocedure

    !procedure style_set_new()
        !$current_artifact_state = 'new'
        style_set('transparent',$new(),4,10)
    !endprocedure

    !procedure style_set_alt()
        !$current_artifact_state = 'alt'
        style_set($alt())
    !endprocedure

    !procedure style_set_remove()
        !$current_artifact_state = 'remove'
        style_set($remove())
    !endprocedure

    !procedure style_set_temporary()
        !$current_artifact_state = 'temporary'
        style_set($temporary(),'','','')
    !endprocedure

    !procedure style_set_remove_future()
        !$current_artifact_state = 'remove_future'
        style_set($remove_future(),'','','')
    !endprocedure

    !function $state()
        !if ($current_artifact_state != '')
            !$color = %call_user_func('$' + $current_artifact_state)
            !$result = '<back:' + $color + '>' + $current_artifact_state + '</back>'
        !endif
        !return $result
    !endfunction

    !function $prototype() 
        !return '<<' + $current_artifact_state + '>>'
    !endfunction
'} END STYLE


<style>
    Component { BackgroundColor #white }
    Boundary  { BackgroundColor #white }
    Interface { BackgroundColor #white }
    Control   { BackgroundColor #white }
    Entity    { BackgroundColor #white }
    database  { BackgroundColor #white }
    Queue     { BackgroundColor #white }

    legend {
        BackgroundColor #white
        LineColor #black
        FontColor #black
    }
    .environment {
        RoundCorner 150
        Shadowing 3
    }
    .service {
        RoundCorner 50
        Shadowing 3
        :depth(3) {
            LineThickness 10
        }
    }
    .transaction {
        LineColor #orange
        'LineStyle 7
        '#line.dashed 
    }
    .done {
        LineColor $existing_link()
        LineThickness 6
        'LineStyle 6
    }
    .ready {
        LineColor $existing_link()
        LineThickness 3
        LineStyle 3
    }
    .wip {
        LineColor $change_link()
        LineThickness 3
        LineStyle 3
    }
    .temporary {
        LineColor $remove()
        LineThickness 3
        'LineStyle 6
    }
    .review {
        LineColor $change_link()
        LineThickness 3
        LineStyle 5
        BackGroundColor white-%lighten($alt(),20)
    }
    .new {
        BackGroundColor $new()
    }
    .change {
        BackGroundColor $change()
    }
    .existing {
        BackGroundColor $existing()
    }
    .live {
        BackGroundColor $existing()
    }
    .remove {
        BackGroundColor $remove()
    }
    .alt {
        BackGroundColor $alt()
    }
    .alternative {
        BackGroundColor $alt()
    }
    .notouch {
        BackGroundColor $notouch()
    }
    .out-of-scope {
        LineColor $alt()
        LineThickness $style__out_of_scope__LineThickness
        BackGroundColor $notouch()|#white
        LineStyle $style__out_of_scope__LineStyle
        DiagonalCorner $style__out_of_scope__DiagonalCorner
    }
    .next-phase{
        LineThickness 3
        BorderThickness 10
        BackGroundColor #white|$new()
        LineStyle 70
        DiagonalCorner 20 
    }
    .hide {
        LineThickness 0
        LineColor #transparent
        FontColor #transparent
    }
arrow {
    LineColor #gray

    .out-of-scope {
        LineColor $alt()
        LineThickness 1
        BackGroundColor $notouch()|$new()
        LineStyle 20
        DiagonalCorner 20
    }
    .wip {
        LineColor $change_link()
        LineThickness 3
        LineStyle 3
    }
    .done {
        LineColor $existing_link()
        LineThickness 3
        LineStyle 20
    }
    .new {
        LineColor $new_link()
    }
    .change {
        LineColor $change_link()
    }
    .existing {
        LineColor $existing_link()
    }
    .live {
        LineColor $existing_link()
    }
    .remove {
        LineColor $remove_link()
    }
    .alt {
        LineColor $alt_link()
    }
    .notouch {
        LineColor $notouch_link()
    }
    .transaction {
        LineColor #orange
        LineStyle 1
        LineThickness 3
    }

    .link {
        ' LineColor $change_link()
        LineThickness 6
    }
    .link_inbound {
        LineColor #green
        LineThickness 6
    }
    .link_outbound {
        LineColor #orange
        LineThickness 6
    }
    .temporary {
        LineColor #HotPink
        LineStyle 10
    }
    .eventually {
        LineStyle 15
    }
    .thick {
        LineThickness 5
    }
    .hide {
        LineThickness 0
        LineColor #transparent
        FontColor #transparent
    }
}
usecase  {
    FontSize 30
    BackgroundColor AliceBlue
    'MaximumWidth 150
    'HorizontalAlignment center
}

component {
    MaximumWidth 50
    HorizontalAlignment center
}

boundary {
    MaximumWidth 50
    HorizontalAlignment left
}

</style>

' aliases start

!procedure Set_Alias($alias)
    !$alias_var = "alias_map__" + $alias
    %set_variable_value($alias_var, $global_last_name)
!endprocedure

!function alias($alias)
    !$alias_var = "alias_map__" + $alias
    !if (%variable_exists($alias_var))
        !$result = %get_variable_value($alias_var)
        !return $result
    !endif
    !return $alias
!endfunction

' aliases end

' Icons Start

!function $strContains($text,$find) 
    !return %strpos($text,$find) >= 0
!endfunction
$assert(0,$strContains('abcd','z'))
$assert(1,$strContains('abcd','c'))

!function $strAppend($source,$append,$separator='')
    !if ( %strlen($source) > 0 && %strlen($append) > 0  )
        !return $source + $separator + $append
    !else
        !return $source + $append 
    !endif
!endfunction
$assert('sourceappend',$strAppend(source,append))
$assert('source append',$strAppend(source,append,' '))

!function $strPrepend($source,$prepend,$separator='')
    !if ( %strlen($source) > 0 && %strlen($prepend) > 0 )
        !return $prepend + $separator + $source
    !else
        !return $prepend + $source
    !endif
!endfunction
$assert('prependsource',$strPrepend(source,prepend))
$assert('prepend source',$strPrepend(source,prepend,' '))

!function $strHasPrefix($text,$find) 
    !if ( %strpos($text,$find) == 0 )
        !return %true()
    !endif
    !return %false()
!endfunction
$assert(1,$strHasPrefix('aaabbb','aaa'),'IsPrefix')
$assert(0,$strHasPrefix('aaabbb','ax'),'No Prefix')

!function $strHasSuffix($text,$find) 
    !$len = %strlen($find)
    !if ($len == 0)
        !return %true()
    !endif
    !$pos = %strpos($text,$find)
    !if ($pos < 0) 
        !return %false()
    !endif
    !return ( %strlen($text) - $pos ) == $len
!endfunction
$assert(1,$strHasSuffix('aaabbb','bbb'),'IsSuffix')
$assert(1,$strHasSuffix('aaabbb',''),'Empty Suffix')
$assert(1,$strHasSuffix('',''),'Empty Suffix')
$assert(0,$strHasSuffix('','bbb'),'Empty Value')
$assert(0,$strHasSuffix('aaa','cbb'),'Empty Value')
$assert(0,$strHasSuffix('aaa','cccc'),'Empty Value')

'moved to the top as assert depends on it
$assert('<a)>-<b)>-<c)>' , $strReplace('<(a)>-<(b)>-<(c)>','<(','<'))
$assert('abc' , $strReplace('  abc  ',' ',''))
$assert('abc' , $strReplace('abc','',''))


'moved to the top as assert depends on it
$assert('~<color:blue>abc',$text_literal('<color:blue>abc'), text_literal)
 
!function $strReverse($text,$map1='<{[(',$map2='>}])')
    !$pos = %strlen($text) -1
    !$result = ''
    !while $pos >= 0
        !$char = %substr($text, $pos, 1)
        !$mapPos = %strpos($map1,$char)
        !if $mapPos >= 0
            !$char = %substr($map2, $mapPos, 1)
        !else
            !$mapPos = %strpos($map2,$char)
            !if $mapPos >= 0
                !$char = %substr($map1, $mapPos, 1)
            !endif
        !endif
        !$result = $result + $char 
        !$pos = $pos - 1  
    !endwhile
    !return $result
!endfunction
$assert('fed<987654321>cba',$strReverse('abc<123456789>def'))
$assert('a-->b',$strReverse('b<--a'))

!function $strSegmentCount($str,$separator=$defaultPartSeparator)
    !if (%strlen($str) <= 0 )
        !return 0
    !endif
    !$res = $str
    !$pos = 1
    !$count = 1
    !while ($pos > 0)
        !$pos = %strpos($res,$separator)
        !if ($pos > 0)
            !$count = $count + 1
            !$res = %substr($res,$pos + %strlen($separator) )
        !endif
    !endwhile
    !return $count
!endfunction
$assert(3,$strSegmentCount(Part1__Part2__Part3,$defaultPartSeparator))
$assert(0,$strSegmentCount('',$defaultPartSeparator))

!function $strSegmentGet($str,$separator=$defaultPartSeparator,$count=(0-1))
    !$res = $str
    !$pos = 1
    !while ($pos >= 0)&&($count!=0)
        !$count = $count - 1
        !$pos = %strpos($res,$separator)
        !if ($pos >= 0)
            !$res = %substr($res,$pos + %strlen($separator) )
        !endif
    !endwhile
    !$pos = %strpos($res,$separator)
    !if ($pos >= 0)
        !$res = %substr($res,0,$pos)
    !endif
'    !$parts = %splitstr($str,$separator) ' Splits by char not by string so is not whats required
'    !foreach $item in $parts
'        !$res = $item
'    !endfor 
    !return $res
!endfunction
$assert(Part1,$strSegmentGet(Part1__Part2__Part3__Part4,'__',0))
$assert(Part4,$strSegmentGet(Part1__Part2__Part3__Part4,'__'))
$assert(Part4,$strSegmentGet('Part1++Part2+Part3+Part4','+'))
$assert('abc+def+-+hij',$strSegmentGet('https://test.net/wiki/spaces//abc+def+-+hij','/'))

!function $GetName($str)
    !$name = $strSegmentGet($str)
    !$name = $strReplace($name,$defaultWordSeparator,' ')
    !return $name
!endfunction
$assert(Part4,$GetName(Part1__Part2__Part3__Part4))

!function $trim($str)
    !$str_parts = %splitstr($str,' ')
    !foreach $item in $str_parts
        !if ($item != '')
            !return $item
        !endif
    !endfor
    !return ''
!endfunction
$assert('abc',$trim(' abc '))


!function $strContainsSegment($list,$find,$separator)
    !if ( $list == $find )
        !return %true()
    !endif
    !if ( $strContains($list,$separator + $find + $separator) )
        !return %true()
    !endif
    !if ( $strHasPrefix($list, $find + $separator) )
        !return %true()
    !endif
    !if ( $strHasSuffix($list, $separator + $find) )
        !return %true()
    !endif
    !return %false()
!endfunction
$assert(0,$strContainsSegment('a|b|c','d','|'))
$assert(1,$strContainsSegment('a','a','|'))
$assert(1,$strContainsSegment('a|b|c','a','|'),"$strContainsSegment('a|b|c','a','|')")
$assert(1,$strContainsSegment('a|b|c','b','|'))
$assert(1,$strContainsSegment('a|b|c','c','|'),"$strContainsSegment('a|b|c','c','|')")

!function $switch_map($input,$output,$ifValue1,$ifValue2='',$ifValue3='',,$ifValue4='',,$ifValue5='',,$ifValue6='') 
    !if ($input == $ifValue1)
        !return $output
    !endif
    !if ($input == $ifValue2 && $ifValue2!='')
        !return $output
    !endif
    !if ($input == $ifValue3 && $ifValue3!='')
        !return $output
    !endif
    !if ($input == $ifValue4 && $ifValue4!='')
        !return $output
    !endif
    !if ($input == $ifValue5 && $ifValue5!='')
        !return $output
    !endif
    !if ($input == $ifValue6 && $ifValue6!='')
        !return $output
    !endif
    !return $input
!end function
$assert($switch_map('a','z','a'),'z')
$assert($switch_map('c','z','a'),'c')
$assert($switch_map('b','z','a','b'),'z')

!global $highlight_start = '<('
!global $highlight_end = ')>'

!function $highlight($str,$start=$highlight_start,$end=$highlight_end,$color='red')
    !$res = $strReplace($str,$start,"<color:" + $color + ">")
    !$res = $strReplace($res,$end,"</color>")
    !return $res
!endfunction
$assert('<color:red>a</color>',$highlight('<(a)>'))
$assert('<color:red>a</color>-<color:red>b</color>-<color:red>c</color>',$highlight('<(a)>-<(b)>-<(c)>'))

!function $link($text, $url)
    !if (%substr($text,0,1) == '/')
        !$text = $strSegmentGet($url,$text)
    !endif
    !$text = $strReplace($text,'+',' ')
    !return "[[" + $url + " " + $text + "]]"
!endfunction
$assert('[[http://google.com aa - bb]]',$link('aa+-+bb','http://google.com'))

!function $entity_icon_map($name)
    !$result = ''
    !$result = $switch_map($name, $result, 'envelope-closed', 'email', 'mail')
    !return $result
!end function


!function $icon_map($value)
    !$result = $value
    !$result = $switch_map( $result, 'timer'          , 'schedule')
    !$result = $switch_map( $result, 'box'            , 'parcel')
    !$result = $switch_map( $result, 'link-intact'    , 'link')
    !$result = $switch_map( $result, 'tablet'         , 'mobile')
    !$result = $switch_map( $result, 'envelope-closed', 'email', 'mail')
    !return $result
!end function
$assert('envelope-closed', $icon_map('email'))

!function $icon($name,$size=$icon_Size,$color=0)
    !$name = $icon_map($name)
    !$result = '<&' + $name + '>'
    !if ($size)
        !$result = '<size:' + $size + '>' + $result + '</size>'
    !endif
    !if ($color)
        !$result = '<color:' + $color + '>' + $result + '</color>'
    !endif
    !return $result
!end function

!function $entity_icon_map($type)
    !$result = $type
    !$result = $switch_map( $result, 'file '          , 'file')
    !if ($result == $type)
        !return ''
    !endif
    !return $trim($result)
!end function
$assert('file',$entity_icon_map('file'))

' Icons End

' relations start

!unquoted procedure relation($string)
    !$comment_rel = "' " + $string
    ' comments seems to be managed by the preprocessor so it cannot be output 
    ' $comment_rel
    !$global_postponed_relations = $global_postponed_relations + %newline() + $string
!end procedure

!$global_postponed_relations ?= ''
!procedure relation_flush()
    $global_postponed_relations
    !$global_postponed_relations = ''
!end procedure

' relations end

' legend Start

!unquoted procedure $componentExample($type,$description='')
        rectangle $type <<$type>> [
            $description
            ]   
!endprocedure

!procedure $legend_States_Content()
    $componentExample(any)
    $componentExample(review)
    $componentExample(new)
    $componentExample(alt)
    $componentExample(wip)
    $componentExample(done)
    $componentExample(ready)
    $componentExample(live)
    $componentExample(notouch)
    $componentExample(change)
    $componentExample(temporary)
    $componentExample(remove)
    '$componentExample('out-of-scope')
        rectangle out_of_scope <<out-of-scope>> [
        ]

    any -> review <<review>>
    review -> new <<new>>
    new -> alt <<alt>>
    alt -> wip <<wip>>
    wip -> ready <<ready>>
    ready -> done <<done>>
    done -> live <<live>> 
    live -> notouch <<notouch>>
    notouch -> change <<change>>
    change -> temporary <<temporary>> 
    temporary -> remove <<remove>>
    remove -> out_of_scope <<out-of-scope>>
!endprocedure

!procedure $legend_Arrows_Content()
    rectangle A
    rectangle B
    rectangle C
    rectangle D
    rectangle E
    rectangle F
    rectangle G
    rectangle H
    rectangle I
    
    A -> B : Information Flow 
    B =\\ C : Push Message 
    C =r(0=> D : API POST
    D <=r(0= E : API GET
    E -> F <<eventually>> : Eventually
    F -|> G : Is A
    G *- H : Composed by
    H -0 I : Used by
!endprocedure

!procedure $legend_Content()
$legend_States_Content()
$legend_Arrows_Content()
!endprocedure

!procedure $legend($open=0)
!if ($open==0)
legend
!endif
{{
scale 0.5
!$commonincludepath ?= "\code\puml\assets"
!$commonincludepath ?= "https://raw.githubusercontent.com/JohnLeyva/plantuml-assets/master"
!include $commonincludepath/style-base.puml
$legend_States_Content()
}}

{{
scale 0.5
!$commonincludepath ?= "\code\puml\assets"
!$commonincludepath ?= "https://raw.githubusercontent.com/JohnLeyva/plantuml-assets/master"
!include $commonincludepath/style-base.puml
$legend_Arrows_Content()
}}
More about [[https://raw.githubusercontent.com/JohnLeyva/plantuml-assets/master/style-simple.svg Conventions]]
<size:8> Plantuml %version() | %date("yyyy-MMM-dd") %filename()</size>
!if ($open==0)
end legend
!endif
!endprocedure

' General Functions

'$legend_Content()
'$legend()

' Legend end

@enduml

