@startuml style

!startsub BASIC

skinparam arrowcolor green
skinparam ArrowThickness 3
skinparam ArrowColor grey
skinparam legendBackgroundColor #white

!function $done($type = "any")
    !return "#lightblue|lightgreen"  
!endfunction

!function $notouch($type = "any")
    !return "#lightgray"  
!endfunction

!function $notouch_link($type = "any")
    !return "#gray"  
!endfunction

!function $exiting($type = "any")
    !return "#lightgreen"  
!endfunction

!function $existing($type = "any")
    !return "#lightgreen"  
!endfunction

!function $existing_link($type = "any")
    !return "#green"  
!endfunction

!function $new($type = "any")
    !return "#cyan"  
!endfunction

!function $new_link($type = "any")
    !return "#blue"  
!endfunction

!function $change($type = "any")
    !return "#yellow"  
!endfunction

!function $remove($type = "any")
    !return "#pink"  
!endfunction

!function $remove_link($type = "any")
    !return "#red"  
!endfunction

!function $temporary($type = "any")
    !return "#cyan|pink"  
!endfunction

!function $remove_future($type = "any")
    !return "#lightgreen|pink"  
!endfunction

!function $change_future($type = "any")
    !return "#lightgreen|yellow"  
!endfunction


!unquoted procedure $black_tag($text='',$desc='')
    note on link #black|lightgray
        <color:#white>$text</color><back:#white><color:#black>$desc</color></back>
    endnote
!endprocedure


legend
<back:#black><color:#white>Text Tag</color></back> | <color:#blue>=</color><back:$new()>New</back> |<back:$existing()>Existing</back> |<back:$change()>Change</back> | <back:$remove()>Remove</back> |  <back:$notouch()>Existing no touch</back> | <back:$done()>Done</back>

<back:$temporary()>Interim Component</back> | <back:$remove_future()>remove in another work stream</back> | <back:$change_future()>change in another work stream</back>
' <size:8> Plantuml %version() | %date("yyyy-MMM-dd") %filename()</size>
end legend

!endsub

!unquoted procedure $example_style($text='')
    component new $new() 
    component existing $existing() 
    component remove $remove()
    component temporary $temporary()
    component notouch $notouch() 
    component done $done()
    component change $change()


    existing -[$remove_link()]-> remove
        $black_tag(remove_link)

    notouch -[$notouch_link()]-> existing
        $black_tag(no_change_link)

    existing --> change
    change --> done
    new -[$new_link()]-> done
    done --> existing 

rectangle "In the scope of another workstream" {
    component remove_future $remove_future() 
    component change_future $change_future()

    existing -[$existing_link()]-> remove_future
        $black_tag(existing_link)
    
    existing --> change_future

    new --> temporary
    temporary --> remove_future
}


!endprocedure

'$example_style()

@enduml